name: Pull Request Checks

on:
  pull_request:
    branches:
      - main  # Run on pull requests to the main branch

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run linting
      - name: Run ESLint
        run: npm run lint

      # Run tests
      - name: Run Tests
        run: npm run test

      # Check if the project builds successfully
      - name: Build the project 
        run: npm run build
