name: Pull Request Checks

on:
  pull_request:
    branches:
      - main  

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

    
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

     
      - name: Install dependencies
        run: npm ci

      
      - name: Run ESLint
        run: npm run lint

      
      - name: Run Tests
        run: npm run test

      # Check if the project builds successfully
      - name: Build the project 
        run: npm run build 
